spring:
    datasource:
        platform: h2
    thymeleaf:
        cache: false
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: ''
    mvc:
        date-format: 'yyyy/MM/dd HH:mm:ss'
    aop:
        proxy-target-class: true
    cache:
        type: guava
server:
    error:
        whitelabel:
            enabled: false
    compression:
        enabled: true
        mime-types: text/html,text/css,application/json
        min-response-size: 2048
security:
    basic:
        enabled: false
management:
    context-path: /manage
    add-application-context-header: false
