spring:
    thymeleaf:
        cache: false
    jpa:
        hibernate:
            ddl-auto: ''
    mvc:
        date-format: 'yyyy/MM/dd HH:mm:ss'
server:
    error:
        whitelabel:
            enabled: false
security:
    basic:
        enabled: false
