spring:
    thymeleaf:
        cache: false
    jpa:
        hibernate:
            ddl-auto: ''
server:
    error:
        whitelabel:
            enabled: false
security:
    basic:
        enabled: false
